title: DLRS Community Documentation
description: Documentation related to the successful application of the DLRS App
timezone: America/Chicago
baseurl: "/" #the subpath of your site, e.g. /blog
url: "https://sfdo-community-sprints.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Information on theme https://just-the-docs.github.io/just-the-docs/
remote_theme: just-the-docs/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Set a path/url to a logo that will be displayed instead of the title
logo: "/asset/images/DLRS_logo.png" 

